# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         EekBoek
version:      0.34
version_from: lib/EB.pm
installdirs:  site
requires:
    Config::IniFiles:              2.38
    DBD::Pg:                       1.41
    DBI:                           1.4
    Getopt::Long:                  2.13
    Term::ReadLine:                0
    Term::ReadLine::Gnu:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
